apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache2-webserver
  labels:
    app: apache2-sana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache2-sana
  template:
    metadata:
      labels:
        app: apache2-sana
    spec:
      containers:
      - name: tomcat-sana
        image: sanashahin2225/apache2:latest
        ports:
        - containerPort: 8181

